export default {
  "Jolteon": require('./sprites/jolteon.gif'),
  "Shiny Jolteon": require('./sprites/shiny_jolteon.gif'),
  "Flareon": require('./sprites/flareon.gif'),
  "Shiny Flareon": require('./sprites/shiny_flareon.gif'),
  "Leafeon": require('./sprites/leafeon.gif'),
  "Shiny Leafon": require('./sprites/shiny_leafeon.gif'),
  "Glaceon": require('./sprites/glaceon.gif'),
  "Shiny Glaceon": require('./sprites/shiny_glaceon.gif'),
  "Sylveon": require('./sprites/sylveon.gif'),
  "Shiny Sylveon": require('./sprites/shiny_sylveon.gif'),
  "Espeon": require('./sprites/espeon.gif'),
  "Shiny Espeon": require('./sprites/shiny_espeon.gif'),
  "Umbreon": require('./sprites/umbreon.gif'),
  "Shiny Umbreon": require('./sprites/shiny_umbreon.gif'),
  "Vaporeon": require('./sprites/vaporeon.gif'),
  "Shiny Vaporeon": require('./sprites/shiny_vaporeon.gif'),
  "Eevee": require('./sprites/eevee.gif'),
  "Shiny Eevee": require('./sprites/shiny_eevee.gif'),
  "Mewtwo": require('./sprites/mewtwo.gif'),
  "Shiny Mewtwo": require('./sprites/shiny_mewtwo.gif')
}